# Token types
#
# EOF (end-of-file) token is used to indicate that
# there is no more input left for lexical analysis

INTEGER = 'INTEGER'
REAL = 'REAL'
INTEGER_CONST = 'INTEGER_CONST'
REAL_CONST = 'REAL_CONST'
STRING = 'STRING'
STRING_CONST = 'STRING_CONST'
PLUS = '+'
MINUS = '-'
MUL = '*'
INTEGER_DIV = 'DIV'
FLOAT_DIV = '/'
LESS_THAN = '<'
GREATER_THAN = '>'
EQUAL = '='
LPAREN = '('
RPAREN = ')'
ID = 'ID'
ASSIGN = ':='
BEGIN = 'BEGIN'
END = 'END'
SEMI = ';'
DOT = '.'
PROGRAM = 'PROGRAM'
VAR = 'VAR'
COLON = ':'
COMMA = ','
PROCEDURE = 'PROCEDURE'
FUNCTION = 'FUNCTION'
CALL = 'CALL'
IF = 'IF'
THEN = 'THEN'
ELSE = 'ELSE'
WHILE = 'WHILE'
DO = 'DO'
FOR = 'FOR'
TO = 'TO'
EOF = 'EOF'
